blank_issues_enabled: false
contact_links:
    - name: Support Question
      url: https://discord.cloudpanel.io
      about: We use GitHub issues only to discuss about CloudPanel bugs and new features.
